In [1]:
import pymongo
import database as db
import pandas as pd
import os

In [ ]:
#for file in format : 2 first letters = ticker, 3rd letter = month expiration and 2 digits year expiration
product = {
    'ML': 'EBM',
    'XR': 'ECO',
    'XB': 'EMA'
}
months = {
    'F': 'JAN',
	'G': 'FEB',
	'H': 'MAR',
	'J': 'APR',
	'K': 'MAY',
	'M': 'JUN',
	'N': 'JUL',
	'Q': 'AUG',
	'U': 'SEP',
	'V': 'OCT',
	'X': 'NOV',
	'Z': 'DEC'
}
directories = ['EBM', 'EMA', 'ECO']
files = [f"{dir}/{f}" for dir in directories for f in os.listdir(f"C:/Users/alexl/Documents/GitHub/agriData/data/data/Futures/{dir}")]
df_list = []
for file in files:
    tmp = pd.read_csv(f'C:/Users/alexl/Documents/GitHub/agriData/data/data/Futures/{file}', skiprows=1).iloc[:-1]
    tmp['Ticker'] = file.split('/')[0]
    tmp['Expiration'] = months.get(file.split('/')[1][2], file.split('/')[1][2]) + file.split('/')[1][3:5]
    df_list.append(tmp)
df = pd.concat(df_list).reset_index(drop=True)

['EBM/MLF02.csv', 'EBM/MLF03.csv', 'EBM/MLF04.csv', 'EBM/MLF05.csv', 'EBM/MLF06.csv', 'EBM/MLF07.csv', 'EBM/MLF08.csv', 'EBM/MLF09.csv', 'EBM/MLF10.csv', 'EBM/MLF11.csv', 'EBM/MLF12.csv', 'EBM/MLF13.csv', 'EBM/MLF14.csv', 'EBM/MLF15.csv', 'EBM/MLH02.csv', 'EBM/MLH03.csv', 'EBM/MLH04.csv', 'EBM/MLH05.csv', 'EBM/MLH06.csv', 'EBM/MLH07.csv', 'EBM/MLH08.csv', 'EBM/MLH09.csv', 'EBM/MLH10.csv', 'EBM/MLH11.csv', 'EBM/MLH12.csv', 'EBM/MLH13.csv', 'EBM/MLH14.csv', 'EBM/MLH15.csv', 'EBM/MLH16.csv', 'EBM/MLH17.csv', 'EBM/MLH18.csv', 'EBM/MLH19.csv', 'EBM/MLH20.csv', 'EBM/MLH21.csv', 'EBM/MLH22.csv', 'EBM/MLH23.csv', 'EBM/MLH24.csv', 'EBM/MLH25.csv', 'EBM/MLH26.csv', 'EBM/MLH27.csv', 'EBM/MLK02.csv', 'EBM/MLK03.csv', 'EBM/MLK04.csv', 'EBM/MLK05.csv', 'EBM/MLK06.csv', 'EBM/MLK07.csv', 'EBM/MLK08.csv', 'EBM/MLK09.csv', 'EBM/MLK10.csv', 'EBM/MLK11.csv', 'EBM/MLK12.csv', 'EBM/MLK13.csv', 'EBM/MLK14.csv', 'EBM/MLK15.csv', 'EBM/MLK16.csv', 'EBM/MLK17.csv', 'EBM/MLK18.csv', 'EBM/MLK19.csv', 'EBM/MLK20.csv', 'EBM/MLK21.csv', 'EBM/MLK22.csv', 'EBM/MLK23.csv', 'EBM/MLK24.csv', 'EBM/MLK25.csv', 'EBM/MLK26.csv', 'EBM/MLK27.csv', 'EBM/MLN02.csv', 'EBM/MLN03.csv', 'EBM/MLN04.csv', 'EBM/MLN05.csv', 'EBM/MLN06.csv', 'EBM/MLQ08.csv', 'EBM/MLQ09.csv', 'EBM/MLQ10.csv', 'EBM/MLQ11.csv', 'EBM/MLQ12.csv', 'EBM/MLU02.csv', 'EBM/MLU03.csv', 'EBM/MLU04.csv', 'EBM/MLU05.csv', 'EBM/MLU06.csv', 'EBM/MLU07.csv', 'EBM/MLU15.csv', 'EBM/MLU16.csv', 'EBM/MLU17.csv', 'EBM/MLU18.csv', 'EBM/MLU19.csv', 'EBM/MLU20.csv', 'EBM/MLU21.csv', 'EBM/MLU22.csv', 'EBM/MLU23.csv', 'EBM/MLU24.csv', 'EBM/MLU25.csv', 'EBM/MLU26.csv', 'EBM/MLX01.csv', 'EBM/MLX02.csv', 'EBM/MLX03.csv', 'EBM/MLX04.csv', 'EBM/MLX05.csv', 'EBM/MLX06.csv', 'EBM/MLX07.csv', 'EBM/MLX08.csv', 'EBM/MLX09.csv', 'EBM/MLX10.csv', 'EBM/MLX11.csv', 'EBM/MLX12.csv', 'EBM/MLX13.csv', 'EBM/MLX14.csv', 'EBM/MLZ15.csv', 'EBM/MLZ16.csv', 'EBM/MLZ17.csv', 'EBM/MLZ18.csv', 'EBM/MLZ19.csv', 'EBM/MLZ20.csv', 'EBM/MLZ21.csv', 'EBM/MLZ22.csv', 'EBM/MLZ23.csv', 'EBM/MLZ24.csv', 'EBM/MLZ25.csv', 'EBM/MLZ26.csv', 'EMA/XBF04.csv', 'EMA/XBF05.csv', 'EMA/XBF06.csv', 'EMA/XBF07.csv', 'EMA/XBF08.csv', 'EMA/XBF09.csv', 'EMA/XBF10.csv', 'EMA/XBF11.csv', 'EMA/XBF12.csv', 'EMA/XBF13.csv', 'EMA/XBF14.csv', 'EMA/XBF15.csv', 'EMA/XBF16.csv', 'EMA/XBF17.csv', 'EMA/XBF18.csv', 'EMA/XBF19.csv', 'EMA/XBF20.csv', 'EMA/XBF21.csv', 'EMA/XBF22.csv', 'EMA/XBH04.csv', 'EMA/XBH05.csv', 'EMA/XBH06.csv', 'EMA/XBH07.csv', 'EMA/XBH08.csv', 'EMA/XBH09.csv', 'EMA/XBH10.csv', 'EMA/XBH11.csv', 'EMA/XBH12.csv', 'EMA/XBH13.csv', 'EMA/XBH14.csv', 'EMA/XBH15.csv', 'EMA/XBH16.csv', 'EMA/XBH17.csv', 'EMA/XBH18.csv', 'EMA/XBH19.csv', 'EMA/XBH20.csv', 'EMA/XBH21.csv', 'EMA/XBH22.csv', 'EMA/XBH23.csv', 'EMA/XBH24.csv', 'EMA/XBH25.csv', 'EMA/XBH26.csv', 'EMA/XBM03.csv', 'EMA/XBM04.csv', 'EMA/XBM05.csv', 'EMA/XBM06.csv', 'EMA/XBM07.csv', 'EMA/XBM08.csv', 'EMA/XBM09.csv', 'EMA/XBM10.csv', 'EMA/XBM11.csv', 'EMA/XBM12.csv', 'EMA/XBM13.csv', 'EMA/XBM14.csv', 'EMA/XBM15.csv', 'EMA/XBM16.csv', 'EMA/XBM17.csv', 'EMA/XBM18.csv', 'EMA/XBM19.csv', 'EMA/XBM20.csv', 'EMA/XBM21.csv', 'EMA/XBM22.csv', 'EMA/XBM23.csv', 'EMA/XBM24.csv', 'EMA/XBM25.csv', 'EMA/XBM26.csv', 'EMA/XBQ03.csv', 'EMA/XBQ04.csv', 'EMA/XBQ06.csv', 'EMA/XBQ07.csv', 'EMA/XBQ08.csv', 'EMA/XBQ09.csv', 'EMA/XBQ10.csv', 'EMA/XBQ11.csv', 'EMA/XBQ12.csv', 'EMA/XBQ13.csv', 'EMA/XBQ14.csv', 'EMA/XBQ15.csv', 'EMA/XBQ16.csv', 'EMA/XBQ17.csv', 'EMA/XBQ18.csv', 'EMA/XBQ19.csv', 'EMA/XBQ20.csv', 'EMA/XBQ21.csv', 'EMA/XBQ22.csv', 'EMA/XBQ23.csv', 'EMA/XBQ24.csv', 'EMA/XBQ25.csv', 'EMA/XBQ26.csv', 'EMA/XBX03.csv', 'EMA/XBX04.csv', 'EMA/XBX05.csv', 'EMA/XBX06.csv', 'EMA/XBX07.csv', 'EMA/XBX08.csv', 'EMA/XBX09.csv', 'EMA/XBX10.csv', 'EMA/XBX11.csv', 'EMA/XBX12.csv', 'EMA/XBX13.csv', 'EMA/XBX14.csv', 'EMA/XBX15.csv', 'EMA/XBX16.csv', 'EMA/XBX17.csv', 'EMA/XBX18.csv', 'EMA/XBX19.csv', 'EMA/XBX20.csv', 'EMA/XBX21.csv', 'EMA/XBX22.csv', 'EMA/XBX23.csv', 'EMA/XBX24.csv', 'EMA/XBX25.csv', 'EMA/XBX26.csv', 'ECO/XRG02.csv', 'ECO/XRG03.csv', 'ECO/XRG04.csv', 'ECO/XRG05.csv', 'ECO/XRG06.csv', 'ECO/XRG07.csv', 'ECO/XRG08.csv', 'ECO/XRG09.csv', 'ECO/XRG10.csv', 'ECO/XRG11.csv', 'ECO/XRG12.csv', 'ECO/XRG13.csv', 'ECO/XRG14.csv', 'ECO/XRG15.csv', 'ECO/XRG16.csv', 'ECO/XRG17.csv', 'ECO/XRG18.csv', 'ECO/XRG19.csv', 'ECO/XRG20.csv', 'ECO/XRG21.csv', 'ECO/XRG22.csv', 'ECO/XRG23.csv', 'ECO/XRG24.csv', 'ECO/XRG25.csv', 'ECO/XRG26.csv', 'ECO/XRJ04.csv', 'ECO/XRK02.csv', 'ECO/XRK03.csv', 'ECO/XRK05.csv', 'ECO/XRK06.csv', 'ECO/XRK07.csv', 'ECO/XRK08.csv', 'ECO/XRK09.csv', 'ECO/XRK10.csv', 'ECO/XRK11.csv', 'ECO/XRK12.csv', 'ECO/XRK13.csv', 'ECO/XRK14.csv', 'ECO/XRK15.csv', 'ECO/XRK16.csv', 'ECO/XRK17.csv', 'ECO/XRK18.csv', 'ECO/XRK19.csv', 'ECO/XRK20.csv', 'ECO/XRK21.csv', 'ECO/XRK22.csv', 'ECO/XRK23.csv', 'ECO/XRK24.csv', 'ECO/XRK25.csv', 'ECO/XRK26.csv', 'ECO/XRM04.csv', 'ECO/XRQ02.csv', 'ECO/XRQ03.csv', 'ECO/XRQ04.csv', 'ECO/XRQ05.csv', 'ECO/XRQ06.csv', 'ECO/XRQ07.csv', 'ECO/XRQ08.csv', 'ECO/XRQ09.csv', 'ECO/XRQ10.csv', 'ECO/XRQ11.csv', 'ECO/XRQ12.csv', 'ECO/XRQ13.csv', 'ECO/XRQ14.csv', 'ECO/XRQ15.csv', 'ECO/XRQ16.csv', 'ECO/XRQ17.csv', 'ECO/XRQ18.csv', 'ECO/XRQ19.csv', 'ECO/XRQ20.csv', 'ECO/XRQ21.csv', 'ECO/XRQ22.csv', 'ECO/XRQ23.csv', 'ECO/XRQ24.csv', 'ECO/XRQ25.csv', 'ECO/XRQ26.csv', 'ECO/XRX01.csv', 'ECO/XRX02.csv', 'ECO/XRX03.csv', 'ECO/XRX04.csv', 'ECO/XRX05.csv', 'ECO/XRX06.csv', 'ECO/XRX07.csv', 'ECO/XRX08.csv', 'ECO/XRX09.csv', 'ECO/XRX10.csv', 'ECO/XRX11.csv', 'ECO/XRX12.csv', 'ECO/XRX13.csv', 'ECO/XRX14.csv', 'ECO/XRX15.csv', 'ECO/XRX16.csv', 'ECO/XRX17.csv', 'ECO/XRX18.csv', 'ECO/XRX19.csv', 'ECO/XRX20.csv', 'ECO/XRX21.csv', 'ECO/XRX22.csv', 'ECO/XRX23.csv', 'ECO/XRX24.csv', 'ECO/XRX25.csv', 'ECO/XRX26.csv']

In [4]:
df = df.rename(columns={'Date Time': 'Date'})
df = df[['Date', 'Ticker', 'Expiration', 'Open', 'High', 'Low', 'Close', 'Volume', 'Open Interest']].sort_values(by='Date').reset_index(drop=True)
df

,Date,Ticker,Expiration,Open,High,Low,Close,Volume,Open Interest
0,2001-09-17,EBM,JAN02,122.00,122.00,121.50,121.75,NaN,NaN
1,2001-09-17,EBM,MAY02,123.25,123.75,123.25,123.75,NaN,NaN
2,2001-09-17,EBM,JUL02,126.00,126.00,126.00,126.00,NaN,NaN
3,2001-09-17,EBM,SEP02,120.00,120.00,120.00,120.00,NaN,NaN
4,2001-09-17,ECO,NOV02,238.00,238.00,236.00,236.00,NaN,NaN
...,...,...,...,...,...,...,...,...,...
150298,2024-07-11,ECO,AUG24,476.00,479.75,475.00,476.50,4448.0,NaN
150299,2024-07-11,ECO,NOV24,483.50,486.50,481.50,482.00,7527.0,NaN
150300,2024-07-11,ECO,AUG25,467.50,471.25,467.25,470.75,7.0,NaN
150301,2024-07-11,EMA,MAR25,211.00,216.00,210.75,215.00,638.0,NaN
150302,2024-07-11,EMA,NOV24,207.25,211.75,207.25,211.25,878.0,NaN